server:
  port: ${PORT:8080}

spring:
  application:
    name: re-shopping-cart-web-app

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/re_shopping_cart_db}
    username: ${DB_USERNAME:cart}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        '[format_sql]': true
        '[highlight_sql]': true

  thymeleaf:
    cache: false